volumes:
  logs:
    driver: local

services:
  slim:
    image: php:8.2-cli-alpine
    working_dir: /var/www
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cp -R .env.sample .env && php -S 0.0.0.0:80 -t public"
    environment:
      docker: "true"
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    networks:
      - challenge_network
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.6-management-alpine
    hostname: my-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - challenge_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    container_name: mysql
    image: mysql:8.0
    platform: linux/arm64
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobsity
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - challenge_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"   # Interfaz web
      - "1025:1025"   # Puerto SMTP
    networks:
      - challenge_network

  worker:
    image: php:8.2-cli-alpine
    working_dir: /var/www
    build:
      context: .
      dockerfile: Dockerfile
    command: php bin/consumer.php
    volumes:
      - .:/var/www
    depends_on:
      - rabbitmq
      - db
    networks:
      - challenge_network

networks:
  challenge_network:
    driver: bridge